# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_playground',
                'doc_host': 'https://kulesa.github.io',
                'git_url': 'https://github.com/kulesa/nbdev_playground',
                'lib_path': 'nbdev_playground'},
  'syms': { 'nbdev_playground.core': { 'nbdev_playground.core.HolaSayer': ('core.html#holasayer', 'nbdev_playground/core.py'),
                                       'nbdev_playground.core.HolaSayer.__init__': ( 'core.html#holasayer.__init__',
                                                                                     'nbdev_playground/core.py'),
                                       'nbdev_playground.core.HolaSayer.say': ('core.html#holasayer.say', 'nbdev_playground/core.py'),
                                       'nbdev_playground.core.foo': ('core.html#foo', 'nbdev_playground/core.py'),
                                       'nbdev_playground.core.say_hello': ('core.html#say_hello', 'nbdev_playground/core.py')}}}
