# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hello', 'HolaSayer']

# %% ../nbs/00_core.ipynb 4
def foo(): pass

# %% ../nbs/00_core.ipynb 5
def say_hello(to):
    "say hello to somebody"
    return f'Hola {to}!'

# %% ../nbs/00_core.ipynb 9
class HolaSayer:
    "Say hola to `to` using `say_hello`"
    def __init__(self, to): self.to = to
        
    def say(self):
        "Do the saying"
        return say_hello(self.to)
